name: ccsmethphase
channels:
  - bioconda
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - pip
  - numpy>=1.15.3
  - statsmodels>=0.12.2
  - scikit-learn>=0.20.1
  - torch>=1.2.0,<=1.7.0
  - pysam>=0.19.0
  - tqdm>=4.64.0
  - pybedtools>=0.8.1
  - pytabix>=0.1
  #- cudatoolkit=11.0
  - scipy
  - samtools>=1.12
  - pbccs>=6.4.0
  - pbmm2>=1.9.0
  - minimap2>=2.23
  - whatshap>=1.4
  # - clair3
  # - primrose>=1.3.0
  # - pandas
  # - parallel=20170422
  - pip:
    - ccsmeth>=0.2.3
