name: ccsmethphase
channels:
  - bioconda
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - pip
  - numpy>=1.15.3
  - statsmodels>=0.12.2
  - scikit-learn>=0.20.1
  - pytorch=1.7.0
  - pysam>=0.19.0
  - tqdm>=4.64.0
  - pybedtools>=0.8.1
  - pytabix>=0.1
  - cudatoolkit=10.2  # 11.0, 11.0.3, 10.2, 10.1, 9.2 for torch 1.7.0
  - scipy
  - pandas
  - samtools>=1.12
  - pbccs>=6.4.0
  - pbmm2>=1.9.0
  - minimap2>=2.23
  - whatshap>=1.4
  - parallel=20191122
  # - clair3
  # - primrose>=1.3.0
  - pip:
    - ccsmeth>=0.2.3
